<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EmployeesScheduler.Domain\EmployeesScheduler.Domain.csproj" />
      <ProjectReference Include="..\EmployeesScheduler.Infrastructure.Postgres\EmployeesScheduler.Infrastructure.Postgres.csproj" />
      <ProjectReference Include="..\EmployeesScheduler.Presenters\EmployeesScheduler.Presenters.csproj" />
    </ItemGroup>

</Project>
